"use client";

import { useState } from "react";
import { useToast } from "@/components/toast-provider";

type Slot = { id: string; startsAt: string; endsAt: string; capacity: number; bookedCount: number; isActive: boolean };
export function DeliverySlotsClient({ initialSlots }: { initialSlots: Slot[] }) {
  const { showToast } = useToast(); const [slots, setSlots] = useState(initialSlots); const [startsAt, setStartsAt] = useState(""); const [endsAt, setEndsAt] = useState(""); const [capacity, setCapacity] = useState("10"); const [saving, setSaving] = useState(false);
  async function create(event: React.FormEvent) { event.preventDefault(); setSaving(true); const response = await fetch("/api/admin/delivery-slots", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ startsAt, endsAt, capacity }) }); const data = await response.json().catch(() => ({})); setSaving(false); if (!response.ok) return showToast(data.error ?? "Slot could not be created", "error"); setSlots((current) => [...current, data.slot].sort((a, b) => a.startsAt.localeCompare(b.startsAt))); setStartsAt(""); setEndsAt(""); showToast("Delivery slot created", "success"); }
  async function toggle(slot: Slot) { const response = await fetch("/api/admin/delivery-slots", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: slot.id, isActive: !slot.isActive }) }); if (!response.ok) return showToast("Slot update failed", "error"); setSlots((current) => current.map((entry) => entry.id === slot.id ? { ...entry, isActive: !entry.isActive } : entry)); }
  return <div className="space-y-4"><form onSubmit={create} className="grid gap-3 rounded-3xl border border-border bg-card p-4 sm:grid-cols-3"><label className="text-sm font-bold">Starts<input required type="datetime-local" value={startsAt} onChange={(event) => setStartsAt(event.target.value)} className="mt-1 h-11 w-full rounded-2xl border border-border bg-background px-3" /></label><label className="text-sm font-bold">Ends<input required type="datetime-local" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} className="mt-1 h-11 w-full rounded-2xl border border-border bg-background px-3" /></label><label className="text-sm font-bold">Capacity<input required type="number" min="1" max="500" value={capacity} onChange={(event) => setCapacity(event.target.value)} className="mt-1 h-11 w-full rounded-2xl border border-border bg-background px-3" /></label><button disabled={saving} className="h-11 rounded-2xl bg-primary text-sm font-black text-white disabled:opacity-50 sm:col-span-3">{saving ? "Creating…" : "Create delivery slot"}</button></form><div className="grid gap-3">{slots.length === 0 ? <p className="rounded-3xl border border-dashed border-border p-8 text-center text-muted-foreground">No upcoming slots.</p> : slots.map((slot) => <article key={slot.id} className="flex items-center justify-between gap-4 rounded-2xl border border-border bg-card p-4"><div><p className="font-black">{new Date(slot.startsAt).toLocaleString("en-IN")}</p><p className="text-sm text-muted-foreground">Until {new Date(slot.endsAt).toLocaleTimeString("en-IN")} · {slot.bookedCount}/{slot.capacity} booked</p></div><button type="button" onClick={() => toggle(slot)} className={`h-10 rounded-xl px-3 text-xs font-black ${slot.isActive ? "bg-primary/10 text-primary" : "bg-slate-100 text-slate-500"}`}>{slot.isActive ? "Active" : "Paused"}</button></article>)}</div></div>;
}
