"use client";

import { useState } from "react";
import { Plus, Save, Trash2 } from "lucide-react";
import { useToast } from "@/components/toast-provider";
import { readApiResponse } from "@/lib/client-api";

type Slab = { id?: string; minKm: number; maxKm: number; fee: number };

export function DeliveryPricingClient({ initialSlabs }: { initialSlabs: Slab[] }) {
  const { showToast } = useToast();
  const [slabs, setSlabs] = useState(initialSlabs);
  const [saving, setSaving] = useState(false);
  function update(index: number, key: keyof Slab, value: number) { setSlabs((current) => current.map((slab, i) => i === index ? { ...slab, [key]: value } : slab)); }
  async function save() { setSaving(true); const response = await fetch("/api/admin/delivery-slabs", { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slabs: slabs.map(({ minKm, maxKm, fee }) => ({ minKm, maxKm, fee })) }) }); const data = await readApiResponse<{ error?: string; fieldErrors?: string[]; slabs?: Slab[] }>(response); setSaving(false); if (!response.ok) return showToast(data.fieldErrors?.join(" ") || data.error || "Pricing update failed", "error"); if (data.slabs) setSlabs(data.slabs); showToast("Delivery pricing updated", "success"); }
  return <div className="space-y-5"><header className="rounded-3xl bg-[linear-gradient(135deg,rgba(15,138,95,0.12),rgba(167,209,41,0.16))] p-5 sm:p-7"><p className="text-xs font-black uppercase text-primary">Pricing</p><h1 className="mt-2 font-display text-3xl font-black">Delivery distance fees</h1><p className="mt-2 text-sm text-muted-foreground">Ranges must start at 0 km, meet exactly and cover the full service radius.</p></header><div className="space-y-3">{slabs.map((slab, index) => <div key={slab.id ?? index} className="grid grid-cols-[1fr_1fr_1fr_auto] gap-2 rounded-2xl border border-border bg-card p-3"><label className="text-xs font-bold">From km<input type="number" step="0.1" min="0" value={slab.minKm} onChange={(e) => update(index, "minKm", Number(e.target.value))} className="mt-1 h-11 w-full rounded-xl border border-border bg-background px-3"/></label><label className="text-xs font-bold">To km<input type="number" step="0.1" min="0.1" value={slab.maxKm} onChange={(e) => update(index, "maxKm", Number(e.target.value))} className="mt-1 h-11 w-full rounded-xl border border-border bg-background px-3"/></label><label className="text-xs font-bold">Fee ₹<input type="number" step="1" min="0" value={slab.fee} onChange={(e) => update(index, "fee", Number(e.target.value))} className="mt-1 h-11 w-full rounded-xl border border-border bg-background px-3"/></label><button aria-label="Remove range" disabled={slabs.length === 1} onClick={() => setSlabs((current) => current.filter((_, i) => i !== index))} className="mt-5 flex h-11 w-11 items-center justify-center rounded-xl bg-red-50 text-red-600 disabled:opacity-40"><Trash2 className="h-4 w-4"/></button></div>)}</div><div className="flex flex-wrap gap-2"><button onClick={() => { const last = slabs.at(-1); setSlabs((current) => [...current, { minKm: last?.maxKm ?? 0, maxKm: (last?.maxKm ?? 0) + 1, fee: last?.fee ?? 30 }]); }} className="inline-flex h-11 items-center gap-2 rounded-2xl border border-border px-4 text-sm font-black"><Plus className="h-4 w-4"/>Add range</button><button disabled={saving} onClick={save} className="inline-flex h-11 items-center gap-2 rounded-2xl bg-primary px-5 text-sm font-black text-white disabled:opacity-50"><Save className="h-4 w-4"/>{saving ? "Saving…" : "Save pricing"}</button></div></div>;
}
